### PR TITLE
fix #194: label --resource-type flag. Flags having certain values can create conditional requirements for other flags to also be set

### LINKED ISSUE #194: label list cannot filter
## Description
It seems `ionosctl label list` cannot properly interpret flags. For some values it even reacts upon, but the resultset is always the same. 

## Expected behavior
`ionosctl label list` interpret and apply flags such as `--datacenter-id`, `--resource-type`, `--server-id` etc.

## Environment
dev, prod.

Go Version: 
```
go version go1.19 darwin/arm64
```
Ionosctl version: 
```
IONOS Cloud CLI version: DEV
SDK GO version: 6.1.0
SDK GO DBaaS Postgres version: v1.0.3
SDK GO Auth version: 1.0.4
```
OS: 
```
darwin/arm64
```
Shell: 
```
zsh
```

## How to Reproduce
With a `dev` account try to list labels. for a datacenter.
`ionosctl label list --datacenter-id ad6eb12c-c20a-4f83-876f-c3a8a9e1fbec`
try with a server
`ionosctl label list --datacenter-id ad6eb12c-c20a-4f83-876f-c3a8a9e1fbec --server-id 03fea0d9-0fde-4351-a3e1-9eea2cfa3a38`
note the result is always the same.
try filter by a resource type
`ionosctl label list --resource-type lan`
`ionosctl label list --resource-type Volume`
I still can see other resource-types in the result set.
when I use volume --resource-type volume it gives me a 404.
```
me@~$ io label list --resource-type volume
Error: 404 Not Found {
  "httpStatus" : 404,
  "messages" : [ {
    "errorCode" : "309",
    "message" : "Resource does not exist"
  } ]
}
```
when I use `Volume`, I still see other resource-types.

### PR DESCRIPTION
**Pull request by avirtopeanu-ionos**
## What does this fix or implement?

#194 

Added custom flag type which ensures value provided for --resource-type is in set of  datacenter,server,volume,ipblock,snapshot . (each type corresponds to a specific api endpoint GET call - and consequently go-sdk list func)

Added requirement for resource-id depending on which resource is wanted

Fix filters, maxResults, orderBy, etc.

## Checklist

- [x] PR name added as appropriate (e.g. `feat:`/`fix:`/`doc:`/`test:`/`refactor:`)
- [x] Tests added or updated
- [x] Documentation updated
- [x] Sonar Cloud Scan
- [ ] Changelog updated and version incremented (label: upcoming release)
- [x] Github Issue linked if any
- [x] Jira task updated

### CODE REVIEW

File: pkg/core/flag.go [hunk 1]
```diff
@@ -188,3 +189,56 @@ func (u uuidFlag) String() string {
...
+			cloudapiv6.DatacenterResource,
+			cloudapiv6.ServerResource,
+			cloudapiv6.VolumeResource,
+			cloudapiv6.IpBlockResource,
+			cloudapiv6.SnapshotResource,
+		},
+	}
+}
+
+func (a *LabelResourceFlag) Set(p string) error {
```
Comment (cristiGuranIonos) [inline pkg/core/flag.go:216]: Maybe SetIfIncluded? Simple setters don't usually return errors

**Review by cristiGuranIonos — APPROVED** [review]

**Review by gabisavu-ionos — APPROVED** [review]

File: pkg/core/flag.go (hunk 1 above)
Comment (avirtopeanu-ionos) [reply pkg/core/flag.go:216]: While I agree this function name could be better, this is an override of the `Set` function that is called by `pflag`. I'm not sure if there's any "entry-points" into `pflag` where we can change its behavior to also check if the flag's values are what we expect them to be

**Comment by avirtopeanu-ionos** [comment]
rebased this branch on top of master

**Review by mimihalescu — APPROVED** [review]
