### PR TITLE
fix #310: camelcase filters key bug

### LINKED ISSUE #310: Filters only work with lowercase property keys
## Description
The use of filters only works with all lowercase property keys. All property keys with lower and uppercase characters give zero results. Verbose output shows, that all filter property keys will be transformed to lowercase.

## Expected behavior
Filters work on all properties.

## Environment

Ionosctl version:
```
ionosctl version v6.6.3
```
OS:
```
Ubuntu 22.04.2 LT
```
Shell:
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

## How to Reproduce
List of snapshots (obfuscated):
```
$ ./ionosctl snapshot list
SnapshotId                             Name                                                                                                          LicenceType   Size   State
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx   some-system-Snapshot-2022-01-01T00:00:00Z           OTHER           300    AVAILABLE
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx   other-system-Snapshot-2023-01-01T00:00:00Z           LINUX            20       AVAILABLE
```
Filter by lowercase property key `name` works:

```
$ ./ionosctl snapshot list --filters name="other-system" -v --output "json"
{
  "Message": "[INFO] Validating 1 filters..."
}
{
  "Message": "[INFO] Valid Filter: name"
}
{
  "Message": "[INFO] Query Parameters set: map[Filters:map[name:[other-system]]], map[Depth:1]"
}
{
  "Message": "[INFO] Request Execution Time: 203.319735ms"
}
{
  "items": [
    {
      "href": "https://api.ionos.com/cloudapi/v6/snapshots/xxx",
      "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "metadata": {
        "createdBy": "xxx",
        "createdByUserId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "createdDate": "2023-01-01T00:00:00Z",
        "etag": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "lastModifiedBy": "xxx",
        "lastModifiedByUserId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "lastModifiedDate": "2023-01-01T00:00:00Z",
        "state": "AVAILABLE"
      },
      "properties": {
        "cpuHotPlug": false,
        "cpuHotUnplug": false,
        "description": "description",
        "discScsiHotPlug": false,
        "discScsiHotUnplug": false,
        "discVirtioHotPlug": false,
        "discVirtioHotUnplug": false,
        "licenceType": "LINUX",
        "location": "de/fra",
        "name": "other-system-Snapshot-2023-01-01T00:00:00Z",
        "nicHotPlug": false,
        "nicHotUnplug": false,
        "ramHotPlug": false,
        "ramHotUnplug": false,
        "secAuthProtection": false,
        "size": 20
      },
      "type": "snapshot"
    }
  ]
}
```
Filter by property key `licenceType` gives zero results

```
./ionosctl snapshot list --filters licenceType="LINUX" --output "json" -v
{
  "Message": "[INFO] Validating 1 filters..."
}
{
  "Message": "[INFO] Valid Filter: licencetype"
}
{
  "Message": "[INFO] Query Parameters set: map[Filters:map[licencetype:[LINUX]]], map[Depth:1]"
}
{
  "Message": "[INFO] Request Execution Time: 178.111543ms"
}
{
  "items": []
}
```

### PR DESCRIPTION
**Pull request by avirtopeanu-ionos**
Fixes #310 - keys being set to lowercase, and as such, filters for keys such as `imageType` don't work, CLI sends `imagetype` to API  

Hacky fix, we manually overwrite the `--filters` values to change keys to those expected by API (by using `availableFilters`). for some reason, `getFilters` doesn't have access to `availableFilters`

The optimal fix would have been to  add `availableFilters` as an argument to `getFilters`, but this would involve touching code in every single command that uses filters /  refactoring this file: https://github.com/ionos-cloud/ionosctl/blob/master/commands/cloudapi-v6/completer/filters.go - both would take a lot of work.

in any case, this PR simply hides the technical debt a bit better rather than being a permanent fix - now it is implied that GetListQueryParams is called after ValidateFilters. We definitely must address this so that these funcs do not have any side effects - honestly we should just use a single function in `Run`

### CODE REVIEW

File: commands/cloudapi-v6/query/query_params.go [hunk 1]
```diff
@@ -112,15 +144,15 @@ func getFilters(args []string, cmd *core.Command) (map[string][]string, error) {
...
 	for _, availableFilters := range availableFiltersObjs {
 		for _, availableFilter := range availableFilters {
 			if strings.ToLower(availableFilter) == strings.ToLower(filter) {
-				return true
+				return availableFilter, nil
 			}
 		}
 	}
-	return false
+	return "", fmt.Errorf("TODO")
```
Comment (cristiGuranIonos) [inline commands/cloudapi-v6/query/query_params.go:155]: todo?

Comment (avirtopeanu-ionos) [reply commands/cloudapi-v6/query/query_params.go]: thanks, renamed to `getFirstValidFilter` and the error is now

```
fmt.Errorf("%s is not case-insensitively equal to any of %s",
			filter, strings.Join(availableFilters, ", "))
```

**Review by cristiGuranIonos — APPROVED** [review]
